import {
  Settings as SettingsIcon,
  ShieldCheck,
  Database,
  Bell,
} from "lucide-react";

const Settings = () => {
  return (
    <div>
      {/* Page Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-white">
          Settings
        </h1>

        <p className="mt-1 text-sm text-slate-500">
          Configure your ScholarNet administration panel.
        </p>
      </div>

      {/* Settings Cards */}
      <div className="grid gap-5 md:grid-cols-2">

        {/* Security */}
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6 transition hover:border-purple-500/20 hover:bg-white/[0.05]">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-purple-500/10 text-purple-400">
            <ShieldCheck size={21} />
          </div>

          <h2 className="mt-5 text-lg font-semibold text-white">
            Security
          </h2>

          <p className="mt-2 text-sm leading-6 text-slate-500">
            Admin authentication and authorization are
            handled securely by the backend.
          </p>
        </div>

        {/* Database */}
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6 transition hover:border-blue-500/20 hover:bg-white/[0.05]">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-500/10 text-blue-400">
            <Database size={21} />
          </div>

          <h2 className="mt-5 text-lg font-semibold text-white">
            Database
          </h2>

          <p className="mt-2 text-sm leading-6 text-slate-500">
            ScholarNet data is managed through the backend
            API and MongoDB database.
          </p>
        </div>

        {/* Notifications */}
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6 transition hover:border-emerald-500/20 hover:bg-white/[0.05]">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-400">
            <Bell size={21} />
          </div>

          <h2 className="mt-5 text-lg font-semibold text-white">
            Notifications
          </h2>

          <p className="mt-2 text-sm leading-6 text-slate-500">
            Scholarship matching and application
            notifications are generated by the backend.
          </p>
        </div>

        {/* Admin Panel */}
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-6 transition hover:border-orange-500/20 hover:bg-white/[0.05]">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-orange-500/10 text-orange-400">
            <SettingsIcon size={21} />
          </div>

          <h2 className="mt-5 text-lg font-semibold text-white">
            Admin Panel
          </h2>

          <p className="mt-2 text-sm leading-6 text-slate-500">
            More administration settings can be added here
            as the platform grows.
          </p>
        </div>

      </div>
    </div>
  );
};

export default Settings;